#!/bin/bash
# ============================================
# WineJS App Installer
# Generated by WineJS Packager v1.0
# ============================================
# App: fifa_2001
# Version: 1.0
# Main EXE: FIFA2001.EXE
# Category: Game
# Port: 6902
# ============================================

# What the generated script does:
#     Verifies WineJS platform - Checks if /opt/winejs exists
#     Creates docker network - Creates winejs-net if missing (important fix!)
#     Creates all necessary directories - /opt/winejs/apps/fifa_2001/, /opt/winejs/kasmvnc-instances/fifa_2001/, etc.
#     Downloads the app - From your Spaces CDN
#     Downloads the icon - To /opt/winejs/translator/public/icons/
#     Creates launch.sh - With proper Wine path detection and dependency installation
#     Creates config.json - With all app metadata for the translator
#     Creates docker-compose.yml - With full gamepad/Wiimote support
#     Fixes permissions - For user 1000 (container user)
#     Creates uninstall script - For clean removal
#     Restarts PM2 translator - So the new app appears in the dashboard
#     Starts the container - Immediately

# When you run this on your WineJS server:

# The app will:
#     Be available at https://yourdomain.com/fifa_2001
#     Have the icon displayed in the Windows 10-style dashboard
#     Be listed alongside MilkShape
#     Auto-start the container when first accessed
#     Have gamepad/Wiimote support built-in

set -e

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log() { echo -e "${GREEN}[$(date '+%H:%M:%S')]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

log "Installing fifa_2001..."

# ============= VERIFY WINEJS PLATFORM =============
log "Verifying WineJS platform..."

if [ ! -d "/opt/winejs" ]; then
    error "WineJS platform not found at /opt/winejs"
    exit 1
fi

if ! docker network ls | grep -q "winejs-net"; then
    log "Creating winejs-net network..."
    docker network create winejs-net
fi

if ! docker images | grep -q "winedrop-base"; then
    log "Warning: winedrop-base image not found"
fi

log "WineJS platform verified"

# ============= FIND NEXT AVAILABLE PORT =============
log "Finding next available port..."

MAX_PORT=6900                              # Start from base port
if [ -d "/opt/winejs/apps" ]; then         # Check if any apps exist
    for config in /opt/winejs/apps/*/config.json; do   # Loop through every app
        if [ -f "$config" ]; then
            PORT=$(grep -o '"port": [0-9]*' "$config" | awk '{print $2}')  # Extract port number
            if [ -n "$PORT" ] && [ "$PORT" -gt "$MAX_PORT" ]; then
                MAX_PORT=$PORT              # Track the highest port used
            fi
        fi
    done
fi
APP_PORT=$((MAX_PORT + 1))                 # Next available port!

log "Using port: $APP_PORT (next available after $MAX_PORT)"

# ============= CREATE APP DIRECTORIES =============
APP_NAME="fifa_2001"
APP_DIR="/opt/winejs/apps/$APP_NAME"
INSTANCE_DIR="/opt/winejs/kasmvnc-instances/$APP_NAME"
WINE_PREFIX="/opt/winejs/wine-prefixes/$APP_NAME"
ICON_DIR="/opt/winejs/translator/public/icons"

mkdir -p "$APP_DIR"
mkdir -p "$INSTANCE_DIR"
mkdir -p "$WINE_PREFIX"
mkdir -p "$ICON_DIR"

cd "$APP_DIR"

# ============= DOWNLOAD APP PACKAGE =============
log "Downloading fifa_2001 package..."
if [[ https://cdn.gitgpt.chat/rtx/wine/fifa_2001.zip == "LOCAL_FILE" ]]; then
    log "Local installation - please copy files manually to $APP_DIR"
else
    curl -L https://cdn.gitgpt.chat/rtx/wine/fifa_2001.zip -o app.zip || error "Failed to download app package"
    unzip -o -q app.zip || error "Failed to unzip app package"
    rm -f app.zip
    
    # FIX: Handle ZIP that extracts to a subfolder
    if [ -d "$APP_DIR/${APP_NAME}" ] && [ "$APP_DIR/${APP_NAME}" != "$APP_DIR" ]; then
        log "Moving files from subfolder..."
        mv "$APP_DIR/${APP_NAME}"/* "$APP_DIR/" 2>/dev/null || true
        rm -rf "$APP_DIR/${APP_NAME}"
        log "Files moved to correct location"
    fi
fi

# ============= DOWNLOAD ICON =============
log "Downloading app icon..."
curl -L https://cdn.gitgpt.chat/rtx/wine/images/fifa_2001.png -o "$ICON_DIR/${APP_NAME}.png" || echo "Failed to download icon, using default"

# ============= USE SELECTED MAIN EXECUTABLE =============
log "Using main executable selected during packaging..."
MAIN_EXE="FIFA2001.EXE"
log "Main executable: $MAIN_EXE"

# First, ensure we're looking in the right place (current directory)
cd "$APP_DIR"

# Look for the selected executable (non-recursive first, then recursive if needed)
if [ -f "$MAIN_EXE" ]; then
    log "✅ Found selected executable: $MAIN_EXE"
else
    log "⚠️ Warning: $MAIN_EXE not found in root directory"
    log "Searching for executable in subdirectories..."
    FOUND_EXE=$(find . -name "$MAIN_EXE" -type f | head -1)
    if [ -n "$FOUND_EXE" ]; then
        MAIN_EXE_PATH="$FOUND_EXE"
        MAIN_EXE=$(basename "$FOUND_EXE")
        MAIN_EXE_DIR=$(dirname "$FOUND_EXE")
        log "✅ Found $MAIN_EXE in $MAIN_EXE_DIR"
        # Move it to root if it's in a subfolder
        if [ "$MAIN_EXE_DIR" != "." ]; then
            log "Moving $MAIN_EXE to root directory..."
            mv "$FOUND_EXE" "$APP_DIR/"
        fi
    else
        log "⚠️ $MAIN_EXE not found, searching for any executable..."
        FOUND_EXE=$(find . -name "*.exe" -type f | grep -v "uninstall" | head -1)
        if [ -n "$FOUND_EXE" ]; then
            MAIN_EXE=$(basename "$FOUND_EXE")
            MAIN_EXE_DIR=$(dirname "$FOUND_EXE")
            log "⚠️ Found alternative: $MAIN_EXE in $MAIN_EXE_DIR"
            # Move it to root
            if [ "$MAIN_EXE_DIR" != "." ]; then
                log "Moving $MAIN_EXE to root directory..."
                mv "$FOUND_EXE" "$APP_DIR/"
            fi
        else
            error "❌ No executable found!"
        fi
    fi
fi

# Final verification
if [ ! -f "$MAIN_EXE" ]; then
    error "❌ Executable $MAIN_EXE not found after search!"
fi

log "✅ Will launch: $MAIN_EXE"

# ============= CREATE LAUNCH SCRIPT WITH AUTO-HEAL =============
log "Generating launch.sh with auto-heal monitor..."
cat > "$APP_DIR/launch.sh" << 'LAUNCH_EOF'
#!/bin/bash

# Function to log with timestamp
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log "🚀 Starting fifa_2001 launch script..."

# Wait for desktop to be fully ready
log "⏳ Waiting for desktop to be ready..."
/usr/bin/desktop_ready
log "✅ Desktop is ready"

# Fix Wine prefix permissions
log "🔧 Fixing Wine prefix permissions..."
sudo chown -R 1000:1000 /home/kasm-user/.wine 2>/dev/null || true

# Initialize Wine prefix if it doesn't exist
if [ ! -d "/home/kasm-user/.wine/drive_c" ]; then
    log "📦 Initializing Wine prefix..."
    WINEPREFIX=/home/kasm-user/.wine wineboot --init
    sleep 5
fi

# Install required DLLs
log "📦 Installing dependencies (this may take a moment)..."
WINEPREFIX=/home/kasm-user/.wine winetricks -q mfc42 vcrun6 vcrun2005 vcrun2008 > /dev/null 2>&1
log "✅ Dependencies installed"

# Find Wine (try multiple locations)
WINE_PATH=$(which wine 2>/dev/null || find /usr -name "wine" -type f 2>/dev/null | head -1)
if [ -z "$WINE_PATH" ]; then
    WINE_PATH="/usr/lib/wine/wine"
fi
log "🔍 Using Wine at: $WINE_PATH"

# Find and launch the app
APP_DIR="/app"
cd "$APP_DIR"
log "📍 Changed directory to: $(pwd)"

# Find the executable (case insensitive)
EXE_FILE="FIFA2001.EXE"
EXE_PATH=$(find . -iname "$EXE_FILE" -type f | head -1 | sed 's|^./||')
if [ -z "$EXE_PATH" ]; then
    # Try to find any exe
    EXE_PATH=$(find . -name "*.exe" -type f | grep -v "uninstall" | head -1 | sed 's|^./||')
fi

if [ -n "$EXE_PATH" ]; then
    log "🎮 Found executable: $EXE_PATH"
    log "🚀 Executing: $WINE_PATH $EXE_PATH"
    
    # Launch the app in background
    $WINE_PATH "$EXE_PATH" &
    APP_PID=$!
    log "✅ App launched with PID: $APP_PID"
    
    # ============= START AUTO-HEAL MONITOR =============
    # Start a background process that checks every 2 seconds if the app is running
    (
        # Wait 5 seconds for app to fully start before monitoring begins
        sleep 5
        
        while true; do
            sleep 2
            # Check if the app process is still running (case insensitive)
            EXE_BASENAME=$(basename "$EXE_PATH")
            if ! pgrep -i -f "$EXE_BASENAME" > /dev/null; then
                log "⚠️ App crashed! Restarting..."
                # Restart the app
                cd /app
                $WINE_PATH "$EXE_PATH" &
                NEW_PID=$!
                log "✅ App restarted with PID: $NEW_PID"
            else
                # Optional: Log heartbeat every minute
                if [ $(( $(date +%s) % 60 )) -lt 5 ]; then
                    log "💓 App is running"
                fi
            fi
        done
    ) &
    MONITOR_PID=$!
    log "🔄 Auto-heal monitor started with PID: $MONITOR_PID"
    # ============= END AUTO-HEAL MONITOR =============
    
    log "✅ App launched with PID: $APP_PID"
  
    # Keep the script running to prevent container from exiting
    log "📡 Monitoring app process (PID: $APP_PID)..."
    wait $APP_PID
    EXIT_CODE=$?
    log "⚠️ App exited with code: $EXIT_CODE"
else
    log "❌ No executable found!"
    ls -la
    exit 1
fi

# If we get here, the app exited
log "👋 Launch script ending"
LAUNCH_EOF

chmod +x "$APP_DIR/launch.sh"

# ============= CREATE CONFIG.JSON =============
log "Generating config.json..."
cat > "$APP_DIR/config.json" << CONF_EOF
{
    "name": "fifa_2001",
    "version": "1.0",
    "description": "fifa_2001 running in browser",
    "executable": "FIFA2001.EXE",
    "port": ${APP_PORT},
    "vnc_password": "f7e766ebd7bd",
    "icon": "/icons/${APP_NAME}.png",
    "category": "Game"
}
CONF_EOF

# ============= CREATE DOCKER-COMPOSE.YML =============
log "Generating docker-compose.yml..."
cat > "$INSTANCE_DIR/docker-compose.yml" << DOCKER_EOF
version: '3.8'

services:
  winejs-${APP_NAME}:
    image: winedrop-base:latest
    container_name: winejs-${APP_NAME}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${APP_PORT}:6901"
    shm_size: "512m"
    environment:
      - APP_NAME=${APP_NAME}
      - START_CMD=/app/launch.sh
      - VNC_PW=f7e766ebd7bd
      - KASM_ALLOW_UNSAFE_AUTH=1
      - VNCOPTIONS=-disableBasicAuth
      - KASM_VIDEO_QUALITY=5
      - KASM_VIDEO_FPS=15
      - KASM_MAX_RESOLUTION=1280x720
      
      - SDL_JOYSTICK_DEVICE=/dev/input/js0
      - SDL_GAMECONTROLLERCONFIG=030000005e040000be02000014010000,XInput Controller,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b8,guide:b16,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:b12,dpdown:b13,dpleft:b14,dpright:b15,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7
      
    volumes:
      - /opt/winejs/apps/${APP_NAME}:/app:ro
      - /var/www/uploads:/uploads:rw
      - /opt/winejs/wine-prefixes/${APP_NAME}:/home/kasm-user/.wine
      - /opt/winejs/kasmvnc-instances/${APP_NAME}/vnc:/home/kasm-user/.vnc
      - /opt/winejs/translator/public/icons/${APP_NAME}.png:/usr/share/kasm/favicon.png:ro
      - /run/udev:/run/udev:ro
      - /dev/shm:/dev/shm:rw
      - /var/run/dbus:/var/run/dbus:ro
      - /var/lib/bluetooth:/var/lib/bluetooth:ro

    devices:
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input:ro
      - /dev/uinput:/dev/uinput:rw

    cap_add:
      - SYS_ADMIN
      - NET_RAW
      - SYS_RAWIO
      - SYS_TTY_CONFIG
    
    group_add:
      - "107"

    security_opt:
      - seccomp:unconfined
      
    networks:
      - winejs-net

networks:
  winejs-net:
    driver: bridge
DOCKER_EOF

# ============= FIX PERMISSIONS =============
log "Fixing permissions..."
VNC_DIR="$INSTANCE_DIR/vnc"
mkdir -p "$VNC_DIR"
chown -R 1000:1000 "$VNC_DIR" 2>/dev/null || true
chown -R 1000:1000 "$WINE_PREFIX" 2>/dev/null || true
chmod -R 755 "$VNC_DIR" 2>/dev/null || true
chmod -R 755 "$WINE_PREFIX" 2>/dev/null || true

# ============= CREATE UNINSTALL SCRIPT =============
log "Creating uninstall script..."
cat > "$(dirname "$APP_DIR")/uninstall_fifa_2001.sh" << UNINSTALL_EOF
#!/bin/bash
# ============================================
# WineJS App Uninstaller
# Generated by WineJS Packager v1.0
# ============================================
# App: fifa_2001
# ============================================

set -e

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log() { echo -e "${GREEN}[$(date '+%H:%M:%S')]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
warn() { echo -e "${YELLOW}[WARNING]${NC} $1"; }

# ============= CRITICAL FIX: Change to safe directory =============
# This prevents the "uv_cwd" error when the current directory gets deleted
cd /tmp || cd /root || cd / || exit 1

log "Uninstalling fifa_2001..."

APP_NAME="fifa_2001"
APP_DIR="/opt/winejs/apps/$APP_NAME"
INSTANCE_DIR="/opt/winejs/kasmvnc-instances/$APP_NAME"
WINE_PREFIX="/opt/winejs/wine-prefixes/$APP_NAME"
ICON_FILE="/opt/winejs/translator/public/icons/${APP_NAME}.png"

# ============= STOP AND REMOVE CONTAINER =============
log "Stopping container..."
if docker ps -a | grep -q "winejs-${APP_NAME}"; then
    cd "$INSTANCE_DIR" 2>/dev/null || true
    docker-compose down 2>/dev/null || docker stop "winejs-${APP_NAME}" 2>/dev/null || true
    docker rm "winejs-${APP_NAME}" 2>/dev/null || true
    log "Container stopped and removed"
else
    log "Container not running"
fi

# ============= REMOVE DOCKER-COMPOSE FILES =============
log "Removing docker-compose configuration..."
if [ -d "$INSTANCE_DIR" ]; then
    rm -rf "$INSTANCE_DIR"
    log "Instance directory removed"
fi

# ============= REMOVE APP FILES =============
log "Removing application files..."
if [ -d "$APP_DIR" ]; then
    rm -rf "$APP_DIR"
    log "App directory removed"
fi

# ============= REMOVE WINE PREFIX =============
log "Removing Wine prefix..."
if [ -d "$WINE_PREFIX" ]; then
    rm -rf "$WINE_PREFIX"
    log "Wine prefix removed"
fi

# ============= REMOVE ICON =============
log "Removing icon..."
if [ -f "$ICON_FILE" ]; then
    rm -f "$ICON_FILE"
    log "Icon removed"
fi

# ============= RELOAD TRANSLATOR =============
log "Reloading WineJS translator..."
if command -v pm2 &> /dev/null; then
    # Make sure we're in a safe directory before running pm2
    cd /tmp || cd /root || cd /
    pm2 restart translator 2>/dev/null || pm2 start /opt/winejs/ecosystem.config.js 2>/dev/null || true
    log "Translator restarted"
fi

# ============= VERIFY REMOVAL =============
echo ""
echo "============================================"
echo "Uninstallation Complete!"
echo "============================================"
echo ""
log "fifa_2001 has been completely removed from your WineJS system"
echo ""
echo "To verify removal:"
echo "   docker ps -a | grep winejs-${APP_NAME}"
echo "   ls /opt/winejs/apps/ | grep ${APP_NAME}"
echo "   ls /opt/winejs/kasmvnc-instances/ | grep ${APP_NAME}"
echo ""
UNINSTALL_EOF

chmod +x "$(dirname "$APP_DIR")/uninstall_fifa_2001.sh"
log "Uninstall script created: $(dirname "$APP_DIR")/uninstall_fifa_2001.sh"

# ============= RELOAD TRANSLATOR =============
log "Reloading WineJS translator to detect new app..."

# Tell the translator to reload apps
if command -v pm2 &> /dev/null; then
    # Restart translator to reload app registry
    pm2 restart translator || pm2 start /opt/winejs/ecosystem.config.js 2>/dev/null || true
    log "Translator restarted"
fi

# ============= START THE CONTAINER =============
log "Starting container for fifa_2001..."
cd "$INSTANCE_DIR"
docker-compose up -d

# Wait a moment for container to start
sleep 3

# Check if container started
if docker ps | grep -q "winejs-${APP_NAME}"; then
    log "Container started successfully"

    # ============= PATCH CONTAINER (like MilkShape) =============
    log "Applying container patches for fifa_2001..."

    # Wait for container to be fully up
    sleep 5

    # Check if container is running
    if docker ps | grep -q "winejs-${APP_NAME}"; then
        log "✅ Container is running, applying patches..."

        # ============= PATCH KASMVNC TO DISABLE CONTROL BAR ANIMATION =============
        log "🔧 Patching KasmVNC to stop control bar animation..."

        # Create the CSS file using printf (no here-document issues)
        docker exec -u 0 "winejs-${APP_NAME}" bash -c 'printf "%s
"         "/* Disable all control bar animations */"         "#noVNC_control_bar,"         "#noVNC_control_bar_handle,"         "#noVNC_control_bar_anchor,"         ".noVNC_control_bar_animated {"         "    transition: none !important;"         "    animation: none !important;"         "}"         ""         "#noVNC_control_bar {"         "    transform: translateX(-280px) !important;"         "    opacity: 0 !important;"         "}"         ""         "#noVNC_control_bar_handle {"         "    transform: translateY(0px) !important;"         "    left: 0 !important;"         "}"         ""         "#noVNC_control_bar.noVNC_open {"         "    transform: translateX(-280px) !important;"         "    opacity: 0 !important;"         "}"         ""         ".noVNC_idle #noVNC_control_bar {"         "    transform: translateX(-280px) !important;"         "}" > /usr/share/kasmvnc/www/no-animation.css' 2>/dev/null || true

        # Inject CSS link
        docker exec -u 0 "winejs-${APP_NAME}" bash -c 'sed -i "/</head>/i <link rel="stylesheet" type="text/css" href="no-animation.css">" /usr/share/kasmvnc/www/index.html' 2>/dev/null || true

        # Create the JavaScript file using printf
        docker exec -u 0 "winejs-${APP_NAME}" bash -c 'printf "%s
"         "(function() {"         "    function forceMinimized() {"         "        const bar = document.getElementById("noVNC_control_bar");"         "        if (bar) {"         "            bar.className = bar.className.replace("noVNC_open", "") + " noVNC_closed";"         "        }"         "        const handle = document.getElementById("noVNC_control_bar_handle");"         "        if (handle) {"         "            handle.style.transform = "translateY(0px)";"         "        }"         "    }"         "    document.addEventListener("DOMContentLoaded", forceMinimized);"         "    setTimeout(forceMinimized, 100);"         "    setTimeout(forceMinimized, 500);"         "})();" > /usr/share/kasmvnc/www/start-minimized.js' 2>/dev/null || true

        # Inject JavaScript
        docker exec -u 0 "winejs-${APP_NAME}" bash -c 'sed -i "/</body>/i <script src="start-minimized.js"></script>" /usr/share/kasmvnc/www/index.html' 2>/dev/null || true

        # Set permissions
        docker exec -u 0 "winejs-${APP_NAME}" bash -c 'chown 1000:1000 /usr/share/kasmvnc/www/no-animation.css /usr/share/kasmvnc/www/start-minimized.js 2>/dev/null || chmod 644 /usr/share/kasmvnc/www/no-animation.css /usr/share/kasmvnc/www/start-minimized.js' 2>/dev/null || true

        log "✅ KasmVNC patched - control bar will start minimized"

        # ============= PANEL KILLER (keeps desktop clean) =============
        log "🔪 Setting up panel killer..."

        # Add panel killer to the container's startup (EXACT MILKSHAPE PATTERN)
        docker exec "winejs-${APP_NAME}" bash -c 'cat >> /home/kasm-user/.bashrc << "EOF"
        # Kill panel immediately
        pkill -f "panel" 2>/dev/null || true
        pkill -f "xfce" 2>/dev/null || true

        # Start a background process that kills panel every 3 seconds
        (
            while true; do
                sleep 3
                # Kill any panels that reappear
                pkill -f "panel" 2>/dev/null || true
                pkill -f "xfce4-panel" 2>/dev/null || true
                pkill -f "lxpanel" 2>/dev/null || true
                
                # Also try to hide any panel windows
                if command -v xdotool &> /dev/null; then
                    PANEL_WINDOW=$(xdotool search --name "panel" 2>/dev/null | head -1)
                    if [ -n "$PANEL_WINDOW" ]; then
                        xdotool windowmove $PANEL_WINDOW -1000 1000 2>/dev/null || true
                    fi
                fi
            done
        ) &
        PANEL_KILLER_PID=$!
        echo "🔄 Persistent panel killer started with PID: $PANEL_KILLER_PID"
        EOF' 2>/dev/null || true

        log "✅ Panel killer configured"

        # Also set fluxbox config to hide toolbar
        docker exec "winejs-${APP_NAME}" bash -c 'mkdir -p /home/kasm-user/.fluxbox &&             echo "session.screen0.toolbar.visible: false" >> /home/kasm-user/.fluxbox/init &&             echo "session.screen0.toolbar.autoHide: true" >> /home/kasm-user/.fluxbox/init' 2>/dev/null || true

        log "✅ Dock/panel killer configured"

        # ============= SET DESKTOP BACKGROUND =============
        log "🎨 Setting desktop background..."

        # Ensure kasm-user has sudo permissions
        docker exec "winejs-${APP_NAME}" bash -c 'echo "kasm-user ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers > /dev/null 2>&1 || true' 2>/dev/null || true

        # Create background script on host and copy to container (like MilkShape)
        cat > /tmp/set-bg-delayed.sh << 'BGEOF'
#!/bin/bash
sleep 10
# Extract domain from the translator config (more reliable)
if [ -f "/opt/winejs/translator/index.js" ]; then
    SERVER_DOMAIN=$(grep "const DOMAIN_NAME" /opt/winejs/translator/index.js | cut -d"'" -f2)
fi
# Fallback to hostname if not found
if [ -z "$SERVER_DOMAIN" ]; then
    SERVER_DOMAIN=$(hostname -f 2>/dev/null || echo "localhost")
fi
echo "🎨 Setting background with domain: $SERVER_DOMAIN"
curl -s "https://img.sdappnet.cloud/?url=${SERVER_DOMAIN}&w=1920&h=1080" -o /tmp/snapshot.png 2>/dev/null
if [ -f /tmp/snapshot.png ]; then
    if command -v xfconf-query &>/dev/null; then
        xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s /tmp/snapshot.png 2>/dev/null
        echo "✅ Desktop background set"
    fi
fi
rm -f /tmp/set-bg-delayed.sh
BGEOF

        # Copy the script into the container and run it
        docker cp /tmp/set-bg-delayed.sh "winejs-${APP_NAME}:/tmp/set-bg-delayed.sh" 2>/dev/null || true
        docker exec -d "winejs-${APP_NAME}" bash -c "chmod +x /tmp/set-bg-delayed.sh && /tmp/set-bg-delayed.sh" 2>/dev/null || true
        rm -f /tmp/set-bg-delayed.sh

        log "✅ Desktop background configured"

    else
        log "⚠️ Container not running, skipping patches"
    fi

else
    log "Container may not have started. Check with: docker logs winejs-${APP_NAME}"
fi

# ============= SHOW ACCESS INFO =============
log "fifa_2001 installed successfully!"
log "Access at: https://$(hostname -f)/${APP_NAME}"
log "VNC Password: f7e766ebd7bd"

echo ""
echo "============================================"
echo "Installation Complete!"
echo "============================================"
echo ""
echo "App: fifa_2001"
echo "URL: https://$(hostname -f)/${APP_NAME}"
echo "VNC Password: f7e766ebd7bd"
echo "Download ZIP: https://cdn.gitgpt.chat/rtx/wine/fifa_2001.zip"
echo "Download Icon: https://cdn.gitgpt.chat/rtx/wine/images/fifa_2001.png"
echo ""
echo "To uninstall: sudo bash $(dirname "$APP_DIR")/uninstall_fifa_2001.sh"
echo ""
